# Generated by Django 4.2.7 on 2024-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration', models.CharField(max_length=255)),
                ('type_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('departure_for_operation', models.DateTimeField()),
                ('arrival_for_operation', models.DateTimeField()),
                ('start_operation', models.DateTimeField()),
                ('stop_operation', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('unit_id', models.IntegerField()),
                ('flight_id', models.IntegerField()),
                ('refueling_point_id', models.IntegerField()),
                ('provider_id', models.IntegerField()),
                ('billed_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('departure_id', models.IntegerField()),
                ('arrival_id', models.IntegerField()),
                ('aircraft_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_quantity', models.IntegerField()),
                ('amount_tax_free', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_including_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('number_delivery_order', models.CharField(max_length=255)),
                ('invoice_nature', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('consumer_id', models.IntegerField()),
                ('currency_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('refueling_point_id', models.IntegerField()),
                ('provider_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('town_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RefuelingPoints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stopover_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stopover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('town_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(max_length=255)),
            ],
        ),
    ]
