# Generated by Django 5.1.1 on 2024-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydata',
            name='action_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencydata',
            name='clinical_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
