# Generated by Django 4.2.7 on 2024-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currencies',
        ),
        migrations.DeleteModel(
            name='DeliveryOrders',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Providers',
        ),
        migrations.DeleteModel(
            name='RefuelingPoints',
        ),
        migrations.DeleteModel(
            name='Stopover',
        ),
        migrations.DeleteModel(
            name='Towns',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='id',
            new_name='Id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='amount_including_tax',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='amount_tax_free',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='consumer_id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_nature',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='number_delivery_order',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='refueling_point_id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='taxes_amount',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='invoices',
            name='Address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='AmountIncludingTax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='AmountTaxFree',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Consumer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='ConsumerCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='CountryCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Currency',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='CurrencyCode',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Fax',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='InvoiceDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='InvoiceNature',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Mail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='NumberDeliveryOrder',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='PaymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Provider',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='ProviderCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='RefuelingPoint',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='RefuelingPointCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='StopOver',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='StopOverCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='TaxesAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='TotalQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Town',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='TownCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Unit',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='UnitCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='UnitType',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
