# Generated by Django 5.1.1 on 2024-10-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emergencydata_action_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydata',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencydata',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AddField(
            model_name='emergencydata',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
