# Generated by Django 4.2.7 on 2024-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_currencies_delete_deliveryorders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100, null=True)),
                ('StartDate', models.DateTimeField(null=True)),
                ('EndDate', models.DateTimeField(null=True)),
                ('TotalQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountTaxFree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountIncludingTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateTimeField(null=True)),
                ('NumberDeliveryOrder', models.CharField(max_length=100)),
                ('InvoiceNature', models.CharField(max_length=100)),
                ('InvoiceDate', models.DateTimeField(null=True)),
                ('CurrencyCode', models.CharField(max_length=10)),
                ('Currency', models.CharField(max_length=100)),
                ('UnitCode', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('UnitType', models.CharField(max_length=100)),
                ('ConsumerCode', models.CharField(max_length=100)),
                ('Consumer', models.CharField(max_length=100)),
                ('ProviderCode', models.CharField(max_length=100)),
                ('Provider', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Fax', models.CharField(max_length=20, null=True)),
                ('Mail', models.EmailField(max_length=254, null=True)),
                ('RefuelingPointCode', models.CharField(max_length=100)),
                ('RefuelingPoint', models.CharField(max_length=100)),
                ('StopOverCode', models.CharField(max_length=100)),
                ('StopOver', models.CharField(max_length=100)),
                ('TownCode', models.CharField(max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('CountryCode', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
