# Generated by Django 5.1.1 on 2024-10-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emergencydata_allergies_emergencydata_animal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencydata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
