# Generated by Django 4.2.7 on 2024-03-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_invoice_delete_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='InvoiceDate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='PaymentDate',
        ),
    ]
