# Generated by Django 4.2.7 on 2024-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_invoice_invoicedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='EndDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='StartDate',
            field=models.CharField(max_length=100),
        ),
    ]
