# Generated by Django 4.2.7 on 2024-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_invoice_enddate_alter_invoice_startdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='CountryCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RefuelingPoint',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RefuelingPointCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='StopOver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='StopOverCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Town',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='TownCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
