# Generated by Django 5.1.1 on 2024-10-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_emergencydata_nombre_morsures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencydata',
            name='douleur',
        ),
        migrations.RemoveField(
            model_name='emergencydata',
            name='gonflement',
        ),
    ]
