# Generated by Django 4.2.7 on 2024-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_aircraft_delete_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('From_Code', models.CharField(max_length=100)),
                ('From_Name', models.CharField(max_length=100)),
                ('To_Code', models.CharField(max_length=100)),
                ('To_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
