# Generated by Django 4.2.7 on 2024-03-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_unitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='Value',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
