# Generated by Django 4.2.7 on 2024-03-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_unitconversion_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitconversion',
            old_name='From_Code',
            new_name='FromCode',
        ),
        migrations.RenameField(
            model_name='unitconversion',
            old_name='From_Name',
            new_name='FromName',
        ),
        migrations.RenameField(
            model_name='unitconversion',
            old_name='To_Code',
            new_name='ToCode',
        ),
        migrations.RenameField(
            model_name='unitconversion',
            old_name='To_Name',
            new_name='ToName',
        ),
    ]
