# Generated by Django 4.2.7 on 2024-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_aircraftname_deliveryorder_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='Code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
