# Generated by Django 4.2.7 on 2024-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_account_notes_account_provider1_account_provider2'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='geography_global_selection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='suppliers_global_selection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
