# Generated by Django 4.2.7 on 2024-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_account_geography_global_selection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('StartDate', models.CharField(max_length=100)),
                ('EndDate', models.CharField(max_length=100)),
                ('Ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('From_Currency_Code', models.CharField(max_length=10)),
                ('From_Currency', models.CharField(max_length=100)),
                ('To_Currency_Code', models.CharField(max_length=10)),
                ('To_Currency', models.CharField(max_length=100)),
            ],
        ),
    ]
