# Generated by Django 4.2.7 on 2024-03-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_exchangerates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerates',
            old_name='From_Currency',
            new_name='FromCurrency',
        ),
        migrations.RenameField(
            model_name='exchangerates',
            old_name='From_Currency_Code',
            new_name='FromCurrencyCode',
        ),
        migrations.RenameField(
            model_name='exchangerates',
            old_name='To_Currency',
            new_name='ToCurrency',
        ),
        migrations.RenameField(
            model_name='exchangerates',
            old_name='To_Currency_Code',
            new_name='ToCurrencyCode',
        ),
    ]
