# Generated by Django 4.2.7 on 2024-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_from_currency_exchangerates_fromcurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='Ratio',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
