# Generated by Django 4.2.7 on 2024-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_exchangerates_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='Ratio',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
