# Generated by Django 4.2.7 on 2024-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_exchangerates_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='PaymentDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
