# Generated by Django 4.2.7 on 2024-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_invoice_paymentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='geography_filter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
