# Generated by Django 4.2.7 on 2024-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_account_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_geo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='start_geo_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
