# Generated by Django 4.2.7 on 2024-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_account_end_geo_date_account_start_geo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
