# Generated by Django 4.2.7 on 2024-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_supplier_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='start_supplier_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
