# Generated by Django 4.2.7 on 2024-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_account_end_supplier_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_global_selection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
