# Generated by Django 4.2.7 on 2024-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_account_time_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='supplier_name_filter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
