# Generated by Django 4.2.7 on 2024-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_account_supplier_name_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='update1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
