# Generated by Django 4.2.7 on 2024-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_account_time_by_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
