# Generated by Django 4.2.7 on 2024-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_account_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aircraft_chart_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
